# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 13:53
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Amount of vouts')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Sum of votes')),
                ('average', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=2, verbose_name='Average rating')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0441\u043e\u0437\u0434\u0430\u043d \u0432')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u0432')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ManyToManyField(related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
    ]
